server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter
        - id: new-service
          uri: lb:http://NEW-SERVICE
          predicates:
            - Path=/api/v1/news/**
          filters:
            - AuthenticationFilter
        - id: comment-service
          uri: lb:http://COMMENT-SERVICE
          predicates:
            - Path=/api/v1/comments/**
          filters:
            - AuthenticationFilter
        - id: auth-service
          uri: lb:http://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AuthenticationFilter

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970